dist: bionic

addons:
  apt:
    packages:
      - socat

language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-pip

install:
  - pip3 install websocket-client

before_script:
  # create a build folder for the out-of-source build
  - mkdir build_tests_coverage
  # switch to build directory
  - cd build_tests_coverage
  # CMakeLists.txt is located at '..' Coverage is on by default.
  - cmake ..

script:
  # once CMake has done its job we just build using make as usual
  - make
  # if the project uses ctest we can run the tests like this
  - make rcom_unit_tests_coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
