name: CI

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.8'     
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install websocket-client
          
      - name: Install dependencies
        run: sudo apt install socat

      - name: Create Build Environment & configure CMake
        working-directory: ${{runner.workspace}}/libr
        shell: bash
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: |
          mkdir build_tests
          cd build_tests
          cmake ..
          
      - name: Build
        working-directory: ${{runner.workspace}}/libr
        run: |
          cd build_tests
          make -j4
          
      - name: Test
        working-directory: ${{runner.workspace}}/libr
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: |
          cd build_tests
          ctest -V -R rcom
      
      - name: debug_path_build
        working-directory: ${{runner.workspace}}/libr
        run: |
          cd build_tests
          echo "pwd build tests"
          pwd
          echo "ls build tests"
          ls -lart
      
      - name: Upload coverage to Codecov
        working-directory: ${{runner.workspace}}/libr
        run: bash <(curl -s https://codecov.io/bash)
      
